# Generated by Django 5.2.17 on 2026-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitywindow',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='busyblock',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')]),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('meetings_per_week__gte', 1)), name='assignment_meetings_per_week_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('duration_slots__gte', 1)), name='assignment_duration_slots_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='availabilitywindow',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='availability_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='busyblock',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='busyblock_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='scheduledclass',
            constraint=models.CheckConstraint(condition=models.Q(('duration_slots__gte', 1)), name='scheduled_class_duration_slots_gte_1'),
        ),
    ]
