# Generated by Django 5.2.17 on 2026-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('timetable', '0002_alter_availabilitywindow_day_alter_busyblock_day_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availabilitywindow',
            constraint=models.CheckConstraint(condition=models.Q(('day__gte', 0), ('day__lte', 5)), name='availability_day_in_range'),
        ),
        migrations.AddConstraint(
            model_name='busyblock',
            constraint=models.CheckConstraint(condition=models.Q(('day__gte', 0), ('day__lte', 5)), name='busyblock_day_in_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduledclass',
            constraint=models.CheckConstraint(condition=models.Q(('day__gte', 0), ('day__lte', 5)), name='scheduled_class_day_in_range'),
        ),
    ]
