# Generated by Django 5.2.17 on 2026-09-03 05:15
# Hand-edited: added split_assignments data migration to convert the removed
# Assignment.meetings_per_week/duration_slots into child MeetingSlot rows.

import django.db.models.deletion
from django.db import migrations, models


def split_assignments(apps, schema_editor):
    Assignment = apps.get_model("timetable", "Assignment")
    MeetingSlot = apps.get_model("timetable", "MeetingSlot")
    for assignment in Assignment.objects.all():
        for order in range(1, assignment.meetings_per_week + 1):
            MeetingSlot.objects.create(
                assignment=assignment,
                order=order,
                mode="sync",
                duration_slots=assignment.duration_slots,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_availabilitywindow_availability_day_in_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('mode', models.CharField(choices=[('async', 'Asynchronous'), ('sync', 'Synchronous'), ('lab', 'Laboratory')], default='sync', max_length=10)),
                ('duration_slots', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='meetingslot',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='timetable.assignment'),
        ),
        migrations.AddConstraint(
            model_name='meetingslot',
            constraint=models.UniqueConstraint(fields=('assignment', 'order'), name='unique_meeting_slot_order'),
        ),
        migrations.AddConstraint(
            model_name='meetingslot',
            constraint=models.CheckConstraint(condition=models.Q(('duration_slots__gte', 1)), name='meeting_slot_duration_slots_gte_1'),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='mode',
            field=models.CharField(blank=True, choices=[('async', 'Asynchronous'), ('sync', 'Synchronous'), ('lab', 'Laboratory')], max_length=10, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='assignment_meetings_per_week_gte_1',
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='assignment_duration_slots_gte_1',
        ),
        migrations.RunPython(split_assignments),
        migrations.RemoveField(
            model_name='assignment',
            name='duration_slots',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='meetings_per_week',
        ),
    ]
